# Generated by Django 5.1.7 on 2025-04-07 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_alter_order_options_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_served', to=settings.AUTH_USER_MODEL),
        ),
    ]
