# Generated by Django 5.1.7 on 2025-04-15 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0008_ingredient_stock_stocktransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('stock_adjust', 'Stock Adjusted'), ('order_status', 'Order Status Changed'), ('table_status', 'Table Status Changed'), ('staff_status', 'Staff Status Changed')], max_length=20)),
                ('description', models.TextField()),
                ('related_model', models.CharField(blank=True, max_length=50)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
