# Generated by Django 5.1.7 on 2025-04-17 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0011_order_delivery_boy'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapp.order'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('stock_adjust', 'Stock Adjusted'), ('order_status', 'Order Status Changed'), ('table_status', 'Table Status Changed'), ('staff_status', 'Staff Status Changed'), ('Deliverd', 'Order Deliverd'), ('accepted', 'Order Accepted')], max_length=20),
        ),
    ]
